#!/usr/bin/env bash
#using for loop to print numbers from 1 t0 100
#numbers divisible by 3 and 5 will be replaced by different words
x=1
for ((x=1; x<=100; x++))
do
	if [ $(( x % 3 )) -eq 0 ] && [ $(( x % 5 )) -eq 0 ]; 
	then
		echo "FizzBuzz"
	elif [ $(( x % 3 )) -eq 0 ];
	then
		echo "Fizz"
	elif [ $(( x % 5 )) -eq 0 ];
	then
		echo "Buzz"
	else
		echo "$x"
	fi
done
