#!/usr/bin/env bash
#script provide information about the file 
x=school
if [ -e "$x" ];
then
echo "school file exists"
if [ -n "$x" ];
then
echo "school file is empty"
else
echo "school file is not empty"
fi
if [ -f "$x" ];
then
echo "school is a regular file"
fi
else
echo "school file does not exist"
fi
